allergyProject/board/urls.py
from django.urls import path
from . import views as boardviews

app_name = 'board'

urlpatterns = [
    path('board/', boardviews.board, name='board'),
    path('bdetail/', boardviews.boarddetail, name='boarddetail'),
]

allergyProject/board/views.py
from django.shortcuts import render

# Create your views here.
def board (request):
    return render(request, 'board.html')

def boarddetail (request):
    return render(request, 'boarddetail.html')

allergyProject/board/templates/board.html
{% extends 'base.html' %}
{% load static %}
<!-- add to django -->
{% block content %}
  <main>
    <div class="container">
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
          <h2>삼겹살</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
          <h2>짜장면</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
          <h2>돈까스</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
          <h2>삼겹살</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
          <h2>짜장면</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
          <h2>돈까스</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
          <h2>삼겹살</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
          <h2>짜장면</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
          <h2>돈까스</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
          <h2>삼겹살</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
          <h2>짜장면</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
          <h2>돈까스</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
          <h2>삼겹살</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
          <h2>짜장면</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
          <h2>돈까스</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
          <h2>삼겹살</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
          <h2>짜장면</h2>
        </a>
      </div>
      <div class="post">
        <a href="{% url 'board:boarddetail' %}">
          <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
          <h2>돈까스</h2>
        </a>
      </div>
    </div>
  </main>
{% endblock %}

allergyProject/board/templates/boarddetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 style="text-align: center;"> 게시글 제목 </h1>
<h3 style="text-align: right;">작성자, 작성시간</h3>
<main>
  <div class="board-details">
      <img src="{% static 'images/food3.jpg' %}" alt="짜장면">
      <div class="recipe">
          <p>1. 양배추,양파,당근,호박을 잘게 썰어 놓습니다.</p>
          <p>2. 포도씨유를 넣어 뜨겁게 달군 후라이팬에 돼지고기를 튀기듯 볶다가 생강청(생강즙)과 간마늘을 넣어줍니다(고기냄새 제거)</p>
          <p>3. 잘볶아진 돼지고기에 양파를 넣어 볶습니다.</p>
          <p>4. 양파가 갈색이 날때까지 볶습니다.
              양파의 풍미가 살아나요.</p>
          <p>5. 준비한 야채들도 넣어 잘 볶아줍3니다.</p>
          <p>6. 야채가 숨이죽고 수분이 나오면 짜장가루를 조금씩 나눠 넣으며 덩어리지지않게 볶아줍니다.</p>
          <p>7. 짜장이 너무 되면 물을 반컵만 넣어 짜장을 완성합니다.</p>
          <p>8. 잘 삶아진 면을 건져 그릇에 담고</p>
          <p>9. 짜장을 올려 짜장면을 완성합니다.</p>
          <p>10.삶은 완두콩도 올려 더욱 맛나게보입니다.</p>
      </div>
  </div>

  <div class="board-like-button-container">
    <button class="like-button" aria-label="Like"></button>
  </div>

</main>

<div id="recommend"></div>
<div class="container">
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
      <h2>삼겹살</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
      <h2>짜장면</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
      <h2>돈까스</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
      <h2>삼겹살</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
      <h2>짜장면</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
      <h2>돈까스</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
      <h2>삼겹살</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
      <h2>짜장면</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
      <h2>돈까스</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
      <h2>삼겹살</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
      <h2>짜장면</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
      <h2>돈까스</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
      <h2>삼겹살</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
      <h2>짜장면</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
      <h2>돈까스</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food2.jpg' %}" alt="Post 1 Thumbnail">
      <h2>삼겹살</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food3.jpg' %}" alt="Post 2 Thumbnail">
      <h2>짜장면</h2>
    </a>
  </div>
  <div class="post">
    <a href="post.html">
      <img src="{% static 'images/food4.jpg' %}" alt="Post 3 Thumbnail">
      <h2>돈까스</h2>
    </a>
  </div>
</div>
{% endblock %}